apiVersion: v1
kind: Secret
metadata:
  name: openshell-credentials-secrets
  namespace: {{ .Values.tenant }}
  labels:
    {{- include "openshell.labels" . | nindent 4 }}
type: Opaque
data:
  placeholder-secret: {{ "placeholder-not-used" | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: openshell-gateway-secrets
  namespace: {{ .Values.tenant }}
  labels:
    {{- include "openshell.labels" . | nindent 4 }}
type: Opaque
data:
  ssh-handshake-secret: {{ randAlphaNum 32 | b64enc | quote }}
