# OpenShift-specific AgentBuild for weather-service agent
# Uses OpenShift internal registry instead of Kind registry
apiVersion: agent.kagenti.dev/v1alpha1
kind: AgentBuild
metadata:
  labels:
    app.kubernetes.io/created-by: e2e-test
    app.kubernetes.io/name: kagenti-operator
    kagenti.io/framework: LangGraph
    kagenti.io/protocol: a2a
    kagenti.io/type: agent
  name: weather-service-build
  namespace: team1
spec:
  mode: dev

  source:
    sourceRepository: "github.com/kagenti/agent-examples.git"
    sourceRevision: "main"
    sourceSubfolder: "a2a/weather_service"
    sourceCredentials:
      name: github-token-secret

  pipeline:
    namespace: kagenti-system
    parameters:
    - name: SOURCE_REPO_SECRET
      value: github-token-secret
    - name: registry-secret
      value: internal-registry-secret

  buildOutput:
    image: "team1/weather-service"
    imageTag: "v0.0.1"
    imageRegistry: "image-registry.openshift-image-registry.svc:5000"
