apiVersion: agent.kagenti.dev/v1alpha1
kind: AgentBuild
metadata:
  labels:
    app.kubernetes.io/created-by: e2e-test
    app.kubernetes.io/name: kagenti-operator
    kagenti.io/framework: Python
    kagenti.io/protocol: mcp
    kagenti.io/type: tool
  name: weather-tool-build
  namespace: team1
spec:
  mode: dev

  source:
    sourceRepository: "github.com/kagenti/agent-examples.git"
    sourceRevision: "main"
    sourceSubfolder: "mcp/weather_tool"
    sourceCredentials:
      name: github-token-secret

  pipeline:
    namespace: team1
    parameters:
    - name: SOURCE_REPO_SECRET
      value: github-token-secret

  buildOutput:
    image: "weather-tool"
    imageTag: "v0.0.1"
    imageRegistry: "registry.cr-system.svc.cluster.local:5000"
