name: Epic
description: For tracking a large feature
title: "epic: "
labels:
  - epic

body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Please describe the problem to be solved and any associated user journeys.
      placeholder: |
        - As a <user type>, I want to <do something>, so that I can <accomplish something>.
        - ...
    validations:
      required: true

  - type: textarea
    id: design
    attributes:
      label: design
      description: Please include any proposed design to address the problem.
      placeholder: |
        - Proposed design: ...

  - type: textarea
    id: goals-non-goals
    attributes:
      label: Goals and non-goals
      description: Please describe any goals and non-goals of this work. For non-goals, sometimes the scope of work is too large.
      placeholder: |
        - Goals: ...
        - Non-goals: ...

  - type: textarea
    id: criteria
    attributes:
      label: Success criteria
      placeholder: |
        - [ ] (Example) X is integrated with Kagenti
    validations:
      required: true

  - type: textarea
    id: stories
    attributes:
      label: Stories to be associated with this epic
      placeholder: |
        - [ ] (Example) Add new API group
        - [ ] (Example) Add Widget API type
        - [ ] (Example) Add WidgetController
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context for the epic here.
