#!/usr/bin/env bash
set -euo pipefail

# Local dev deploy script for ui-v2
# Usage: ./dev-deploy.sh [--cluster-name NAME] [--frontend-image REPO] [--backend-image REPO]

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

KIND_CLUSTER="kagenti"
FRONTEND_REPO="ghcr.io/kagenti/kagenti-ui-v2"
BACKEND_REPO="ghcr.io/kagenti/kagenti-backend"

while [[ ${#} -gt 0 ]]; do
  case "$1" in
    --cluster-name) KIND_CLUSTER="$2"; shift 2 ;;
    --frontend-image) FRONTEND_REPO="$2"; shift 2 ;;
    --backend-image) BACKEND_REPO="$2"; shift 2 ;;
    -h|--help) echo "Usage: $0 [--cluster-name NAME] [--frontend-image REPO] [--backend-image REPO]"; exit 0 ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

cd "$REPO_ROOT"

# generate tag from git short commit and timestamp
GIT_SHORT="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
TS="$(date +%Y%m%d%H%M%S)"
TAG="${GIT_SHORT}-${TS}"

FRONTEND_IMAGE="${FRONTEND_REPO}:${TAG}"
BACKEND_IMAGE="${BACKEND_REPO}:${TAG}"

echo "Tag: $TAG"
echo "Frontend image: $FRONTEND_IMAGE"
echo "Backend image:  $BACKEND_IMAGE"

echo "Building frontend..."
docker build -t "$FRONTEND_IMAGE" -f "$REPO_ROOT/kagenti/ui-v2/Dockerfile" "$REPO_ROOT/kagenti/ui-v2" --load

echo "Building backend..."
docker build -t "$BACKEND_IMAGE" -f "$REPO_ROOT/kagenti/backend/Dockerfile" "$REPO_ROOT/kagenti/backend" --load

echo "Loading images into kind cluster '$KIND_CLUSTER'..."
kind load docker-image --name "$KIND_CLUSTER" "$FRONTEND_IMAGE" "$BACKEND_IMAGE"

KUSTOMIZE_DIR="$REPO_ROOT/deployments/ui-v2/kubernetes"

echo "Preparing temporary kustomize directory to avoid repo modification..."
TMP_DIR="$(mktemp -d)"
cleanup() {
  rm -rf "$TMP_DIR"
}
trap cleanup EXIT

cp -a "$KUSTOMIZE_DIR/." "$TMP_DIR/"
KUSTOM_FILE="$TMP_DIR/kustomization.yaml"

if [ -f "$KUSTOM_FILE" ]; then
  awk '/^images:/{exit} {print}' "$KUSTOM_FILE" > "$KUSTOM_FILE.tmp"
  cat >> "$KUSTOM_FILE.tmp" <<EOF
images:
  - name: ghcr.io/kagenti/kagenti-backend
    newName: ${BACKEND_REPO}
    newTag: ${TAG}
  - name: ghcr.io/kagenti/kagenti-ui-v2
    newName: ${FRONTEND_REPO}
    newTag: ${TAG}
EOF
  mv "$KUSTOM_FILE.tmp" "$KUSTOM_FILE"
else
  cat > "$KUSTOM_FILE" <<EOF
# kustomization autogenerated by dev-deploy.sh
images:
  - name: ghcr.io/kagenti/kagenti-backend
    newName: ${BACKEND_REPO}
    newTag: ${TAG}
  - name: ghcr.io/kagenti/kagenti-ui-v2
    newName: ${FRONTEND_REPO}
    newTag: ${TAG}
EOF
fi

echo "Applying manifests from temporary directory..."
kubectl apply -k "$TMP_DIR"

echo "Waiting for rollouts..."
kubectl -n kagenti-system rollout status deployment/kagenti-ui-v2
kubectl -n kagenti-system rollout status deployment/kagenti-backend

echo "Done. Frontend and backend deployed with tag $TAG (no repo changes)"
