# Copyright 2025 IBM Corp.
# Licensed under the Apache License, Version 2.0
#
# Example MCPServer manifest for Weather Tool (Shipwright-built).
# Apply this after the Shipwright BuildRun completes successfully.
# Use the output image from the BuildRun status.

apiVersion: toolhive.io/v1alpha1
kind: MCPServer
metadata:
  name: weather-tool
  namespace: team1
  labels:
    kagenti.io/type: tool
    kagenti.io/built-by: shipwright
    kagenti.io/build-name: weather-tool
    app.kubernetes.io/name: weather-tool
    app.kubernetes.io/component: mcp-tool
  annotations:
    kagenti.io/description: "Weather lookup tool that provides weather forecasts"
    kagenti.io/framework: "Python"
spec:
  # Image from Shipwright BuildRun output
  # Replace with actual digest from buildrun.status.output.image
  image: registry.cr-system.svc.cluster.local:5000/weather-tool:v0.0.1

  # MCP protocol type
  protocol: streamable_http

  # Replicas for high availability
  replicas: 1

  # Resource limits and requests
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"

  # Optional: Environment variables
  env:
    - name: LOG_LEVEL
      value: "INFO"
    # Example: reference a secret
    # - name: API_KEY
    #   valueFrom:
    #     secretKeyRef:
    #       name: weather-api-secret
    #       key: api-key

  # Optional: Service ports configuration
  # ports:
  #   - containerPort: 8000
  #     servicePort: 80
  #     protocol: TCP

---
# MCPServer with image digest (more secure/reproducible)
apiVersion: toolhive.io/v1alpha1
kind: MCPServer
metadata:
  name: weather-tool-pinned
  namespace: team1
  labels:
    kagenti.io/type: tool
    kagenti.io/built-by: shipwright
spec:
  # Use image digest for reproducibility
  # Get this from buildrun.status.output.digest
  image: registry.cr-system.svc.cluster.local:5000/weather-tool@sha256:abc123def456...
  protocol: streamable_http
  replicas: 1
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"

---
# MCPServer from external registry
apiVersion: toolhive.io/v1alpha1
kind: MCPServer
metadata:
  name: weather-tool-external
  namespace: team1
  labels:
    kagenti.io/type: tool
spec:
  image: quay.io/myorg/weather-tool:v0.0.1
  protocol: streamable_http
  replicas: 1
  # Pull secret for private registry
  imagePullSecrets:
    - name: quay-pull-secret
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
