name: Add Issues and PRs to Kagenti Prioritization Project

on:
  workflow_call: 

jobs:
  add-to-project:
    runs-on: ubuntu-latest

    steps:
      - name: Add issue or PR to Kagenti Project
        continue-on-error: true # To prevent duplicate additions
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/kagenti/projects/<PROJECT_NUMBER>
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}