# OpenShift MCPServer for weather-tool
# Uses the OpenShift internal registry image built by BuildConfig
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: weather-tool
  namespace: team1
  labels:
    app.kubernetes.io/created-by: e2e-test
    app.kubernetes.io/name: toolhive-operator
    kagenti.io/framework: Python
    kagenti.io/protocol: mcp
    kagenti.io/type: tool
  annotations:
    description: "Weather MCP tool for E2E testing via Toolhive (OpenShift)"
spec:
  # Image built by OpenShift BuildConfig
  # Uses the internal registry path: image-registry.openshift-image-registry.svc:5000/<namespace>/<imagestream>:<tag>
  image: image-registry.openshift-image-registry.svc:5000/team1/weather-tool:v0.0.1

  # HTTP transport for MCP (weather-tool exposes HTTP endpoint at /mcp)
  transport: sse

  # Environment variables for the weather-tool
  env:
    - name: PORT
      value: "8000"
    - name: HOST
      value: "0.0.0.0"
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: "http://otel-collector.kagenti-system.svc.cluster.local:8335"
    - name: KEYCLOAK_URL
      value: "http://keycloak.keycloak.svc.cluster.local:8080"
    - name: UV_NO_CACHE
      value: "1"
    - name: MCP_URL
      value: "http://weather-tool:8000/mcp"
    - name: LLM_API_BASE
      value: "http://dockerhost:11434/v1"
    - name: LLM_API_KEY
      value: "dummy"
    - name: LLM_MODEL
      value: "qwen2.5:0.5b"

  # Resource limits (matching the Agent CR)
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi
